# Generated by Django 6.0.5 on 2026-06-13 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userhealthprofile_usermedication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('predicted_disease', models.CharField(max_length=200)),
                ('confidence_score', models.IntegerField()),
                ('severity', models.CharField(max_length=20)),
                ('reasoning', models.TextField()),
                ('suggested_drugs', models.JSONField(default=list)),
                ('common_symptoms_matched', models.JSONField(default=list)),
                ('full_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
