# Generated by Django 6.0.5 on 2026-06-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_symptomprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
