# Generated by Django 6.0.5 on 2026-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthprofile',
            name='bp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='na_to_k',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
