# Generated by Django 6.0.5 on 2026-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_user_type_delete_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient'), ('pharmacy_owner', 'Pharmacy Owner'), ('both', 'Both')], default='patient', max_length=20),
        ),
    ]
