# Generated by Django 6.0.5 on 2026-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhealthprofile',
            name='na_to_k',
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Any known allergies', null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='blood_sugar',
            field=models.CharField(blank=True, help_text='Fasting blood sugar level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Chronic conditions like diabetes, hypertension, etc.', null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
