# Generated by Django 6.0.5 on 2026-06-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_userhealthprofile_na_to_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, help_text='List of medicines from the prescription (one per line)'),
        ),
    ]
