# Generated by Django 6.0.5 on 2026-06-17 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prescription_medicines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosed_disease',
            field=models.CharField(default='No disease', help_text='What was diagnosed?', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, help_text="Doctor's name", max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.CharField(blank=True, help_text='Hospital/Clinic name', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload prescription image (optional)', null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.JSONField(default=list, help_text='List of prescribed medicines with details'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional instructions or notes'),
        ),
    ]
