# Generated by Django 6.0.5 on 2026-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomprediction',
            name='drug_interactions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='symptomprediction',
            name='safety_precautions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='symptomprediction',
            name='when_to_see_doctor',
            field=models.TextField(blank=True),
        ),
    ]
