# Generated by Django 6.0.5 on 2026-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Full name of the pharmacy owner', max_length=200),
        ),
    ]
